import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <nav className='bg-orange-100 p-3 border'>
           <h1 className="font-bold text-lg ">GIPHY</h1>
           
         </nav>
        {children}</body>
    </html>
  )
}
